// GENERATED by source/build.mjs from catalogue.source.json. Do not edit by hand.
export default {
 "settings": {
  "deposit": 500,
  "lead_days": 1,
  "horizon_days": 60,
  "weekend_surcharge": 0,
  "arrival_note": "Your engineer will confirm your arrival time with you before the day.",
  "phone": "07988 991963",
  "price_note": "Fixed price for the work described. Anything extra found on site is agreed with you first."
 },
 "products": [
  {
   "id": "worcester-4000-25",
   "priority": 1,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 4000 25kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": 24,
   "dhw_flow_lpm": 10.2,
   "efficiency_pct": 94,
   "erp": "A",
   "warranty_years": 10,
   "warranty_note": "Up to 10 years when installed and registered to Worcester Bosch terms",
   "dimensions_mm": "724 x 400 x 310",
   "image": null,
   "availability": "available",
   "description": "A reliable, quiet combi from a UK manufacturer, suited to smaller homes with one bathroom.",
   "benefits": [
    "Up to 10-year warranty",
    "Quiet, well-known UK brand",
    "Compact wall-mounted size"
   ],
   "price": 2671,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-4000-30",
   "priority": 2,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 4000 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": 24,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": 94,
   "erp": "A",
   "warranty_years": 10,
   "warranty_note": "Up to 10 years when installed and registered to Worcester Bosch terms",
   "dimensions_mm": "724 x 400 x 310",
   "image": null,
   "availability": "available",
   "description": "Higher hot-water flow for busier households. Heating output is the same as the 25kW.",
   "benefits": [
    "Stronger hot-water flow",
    "Up to 10-year warranty",
    "Quiet, well-known UK brand"
   ],
   "price": 2770,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-max-30",
   "priority": 3,
   "manufacturer": "Ideal",
   "model": "Logic Max Combi2 C30",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": 24.2,
   "dhw_flow_lpm": 12.4,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": 10,
   "warranty_note": "10 years parts and labour when registered within 30 days and serviced annually",
   "dimensions_mm": "700 x 395 x 278",
   "image": "ideal-logic-max-c24-combi-boiler.png",
   "availability": "available",
   "description": "Compact UK-made combi with an Ideal system filter included. Higher hot-water output for larger households.",
   "benefits": [
    "10-year parts and labour warranty",
    "Compact UK-made boiler",
    "System filter included"
   ],
   "price": 2695,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "navien-ncb300-30",
   "priority": 4,
   "manufacturer": "Navien",
   "model": "NCB300 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": 24,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": 5,
   "warranty_note": "5 year warranty",
   "dimensions_mm": "680 x 395 x 283",
   "image": null,
   "availability": "available",
   "description": "A compact, good-value combi with strong hot-water flow.",
   "benefits": [
    "Lowest price of our combis",
    "Strong hot-water flow",
    "Very compact"
   ],
   "price": 2149,
   "boiler_price": null,
   "installation_price": null
  }
 ],
 "conversion": {
  "id": "conversion",
  "label": "Convert to a combi boiler",
  "description": "We remove your hot water cylinder and tanks and alter the pipework so a combi can be fitted.",
  "price": 940
 },
 "moves": [
  {
   "id": "same_room",
   "label": "Same room, different position",
   "price": 1095
  },
  {
   "id": "utility",
   "label": "Utility room",
   "price": 1294
  },
  {
   "id": "kitchen",
   "label": "Kitchen",
   "price": 1294
  },
  {
   "id": "garage",
   "label": "Garage",
   "price": 1294
  },
  {
   "id": "airing",
   "label": "Airing cupboard",
   "price": 1294
  },
  {
   "id": "bedroom",
   "label": "Bedroom",
   "price": 1294
  },
  {
   "id": "loft",
   "label": "Loft or attic",
   "price": 1493
  },
  {
   "id": "other",
   "label": "Somewhere else",
   "price": null
  }
 ],
 "extras": [
  {
   "id": "flush",
   "group": "care",
   "label": "Heating system flush",
   "description": "An in-depth clean of your heating system to improve efficiency and help your new boiler last.",
   "price": 198,
   "max": 1
  },
  {
   "id": "scale",
   "group": "care",
   "label": "In-line scale reducer",
   "description": "Helps stop limescale forming in your boiler and pipework. Worth having in a hard water area.",
   "price": 65,
   "max": 1
  },
  {
   "id": "trv",
   "group": "rads",
   "label": "Thermostatic radiator valve (TRV)",
   "description": "Set the temperature room by room. Building Regulations expect one on every radiator except in the room with the main thermostat.",
   "price": 40,
   "max": 20,
   "unit": "each"
  },
  {
   "id": "rad",
   "group": "rads",
   "label": "Replace a radiator (like for like)",
   "description": "Swap an old radiator for a new one of the same size, with a TRV fitted.",
   "price": 149,
   "max": 10,
   "unit": "each"
  },
  {
   "id": "ctl_wifi",
   "group": "controls",
   "exclusive": true,
   "label": "Wi-Fi smart thermostat",
   "description": "Control your heating from your phone.",
   "price": 79,
   "max": 1
  },
  {
   "id": "ctl_smart",
   "group": "controls",
   "exclusive": true,
   "label": "Advanced smart thermostat",
   "description": "A smart thermostat designed to give you more control and cut your gas use.",
   "price": 99,
   "max": 1
  },
  {
   "id": "ctl_hive",
   "group": "controls",
   "exclusive": true,
   "label": "Hive Thermostat Mini",
   "description": "Hive's smart thermostat, supplied and set up for you.",
   "price": 267,
   "max": 1
  },
  {
   "id": "ctl_reconnect",
   "group": "controls",
   "exclusive": true,
   "label": "Reconnect my existing Hive or Nest",
   "description": "You must already own it. We reconnect it to your new boiler on the day.",
   "price": 5,
   "max": 1
  }
 ],
 "groups": {
  "care": "System care",
  "rads": "Radiators and valves",
  "controls": "Heating controls"
 },
 "included": [
  "Installation by a Gas Safe registered engineer",
  "Removal and disposal of your old boiler",
  "Standard flue kit for your new boiler",
  "Programmable room thermostat",
  "Testing, commissioning and a walk-through of the controls"
 ]
};
