// GENERATED from the Plumb Centre price list (08/10/2026) by build_catalogue.py. Prices = boiler pack x 1.15 handling + installation, min £2,800.
export default {
 "settings": {
  "deposit": 500,
  "lead_days": 1,
  "horizon_days": 60,
  "weekend_surcharge": 0,
  "arrival_note": "Your engineer will confirm your arrival time with you before the day.",
  "phone": "07988 991963",
  "price_note": "Fixed price for a standard like-for-like combi installation. Anything extra found on site is agreed with you first."
 },
 "products": [
  {
   "id": "worcester-4000-25",
   "priority": 1,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 4000 25kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.2,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.worcester-bosch.co.uk/img/worcester-bosch/product_images/no_roundel/92ef5fc8-dfc7-4473-9563-7a2f9216b1fa.png",
   "availability": "available",
   "description": "Worcester Bosch Greenstar 4000 25kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "25 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3750,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-4000-30",
   "priority": 2,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 4000 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.worcester-bosch.co.uk/img/worcester-bosch/product_images/no_roundel/92ef5fc8-dfc7-4473-9563-7a2f9216b1fa.png",
   "availability": "available",
   "description": "Worcester Bosch Greenstar 4000 30kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3995,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecofit-825",
   "priority": 3,
   "manufacturer": "Vaillant",
   "model": "ecoFIT pure 825",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.2,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://professional.vaillant.co.uk/images/products/boilers/ecofit-pure/ecofit-pure-combi-2576892-format-flex-height.jpg",
   "availability": "available",
   "description": "Vaillant ecoFIT pure 825 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "25 kW hot-water output",
    "Horizontal flue included",
    "Boiler protection kit included"
   ],
   "price": 3730,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecofit-830",
   "priority": 4,
   "manufacturer": "Vaillant",
   "model": "ecoFIT pure 830",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://professional.vaillant.co.uk/images/products/boilers/ecofit-pure/ecofit-pure-combi-2576892-format-flex-height.jpg",
   "availability": "available",
   "description": "Vaillant ecoFIT pure 830 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Boiler protection kit included"
   ],
   "price": 3830,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-max-24",
   "priority": 5,
   "manufacturer": "Ideal",
   "model": "Logic Max Combi2 C24",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": "ideal-logic-max-c24-combi-boiler.png",
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/3S8Lrd4lgDMSNFb4uJbI5l/a672e68357108384a8275cf03e631902/Logic_MAX_Combi2_FO.png?w=480&h=835&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Logic Max Combi2 C24 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Heating control included"
   ],
   "price": 3620,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-max-30",
   "priority": 6,
   "manufacturer": "Ideal",
   "model": "Logic Max Combi2 C30",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": "ideal-logic-max-c24-combi-boiler.png",
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/3S8Lrd4lgDMSNFb4uJbI5l/a672e68357108384a8275cf03e631902/Logic_MAX_Combi2_FO.png?w=480&h=835&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Logic Max Combi2 C30 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3775,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-630",
   "priority": 7,
   "manufacturer": "Baxi",
   "model": "630 Combi 2 (30kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-600-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 630 Combi 2 (30kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3360,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-1000-24",
   "priority": 8,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 1000 24kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar 1000 24kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2980,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-1000-30",
   "priority": 9,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 1000 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar 1000 30kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3065,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-2000-24",
   "priority": 10,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 2000 24kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar 2000 24kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3310,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-2000-30",
   "priority": 11,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 2000 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar 2000 30kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3395,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-cdi-28",
   "priority": 12,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar CDi Compact 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar CDi Compact 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3655,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-cdi-36",
   "priority": 13,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar CDi Compact 36kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.7,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Worcester Bosch Greenstar CDi Compact 36kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "36 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4120,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-8000-32",
   "priority": 14,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 8000+ 32kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 13.1,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.worcester-bosch.co.uk/img/products/8000_boiler.png",
   "availability": "available",
   "description": "Worcester Bosch Greenstar 8000+ 32kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "32 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4035,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "worcester-8000-36",
   "priority": 15,
   "manufacturer": "Worcester Bosch",
   "model": "Greenstar 8000+ 36kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.7,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.worcester-bosch.co.uk/img/products/8000_boiler.png",
   "availability": "available",
   "description": "Worcester Bosch Greenstar 8000+ 36kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "36 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4295,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-max-35",
   "priority": 16,
   "manufacturer": "Ideal",
   "model": "Logic Max Combi2 C35",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": "ideal-logic-max-c24-combi-boiler.png",
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/3S8Lrd4lgDMSNFb4uJbI5l/a672e68357108384a8275cf03e631902/Logic_MAX_Combi2_FO.png?w=480&h=835&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Logic Max Combi2 C35 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "35 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3970,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-24",
   "priority": 17,
   "manufacturer": "Ideal",
   "model": "Logic Combi2 C24",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/1Hq6Ug8iK7WCC83eNw0Uiu/7bea0fb8fb81d6a33e5e355d3842f785/Logic_Combi2_C24_FO_1.png?w=480&h=834&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Logic Combi2 C24 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3485,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-logic-30",
   "priority": 18,
   "manufacturer": "Ideal",
   "model": "Logic Combi2 C30",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/1Hq6Ug8iK7WCC83eNw0Uiu/7bea0fb8fb81d6a33e5e355d3842f785/Logic_Combi2_C24_FO_1.png?w=480&h=834&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Logic Combi2 C30 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3650,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-imini-30",
   "priority": 19,
   "manufacturer": "Ideal",
   "model": "i-Mini C30",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Ideal i-Mini C30 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3065,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "ideal-vogue-max-40",
   "priority": 20,
   "manufacturer": "Ideal",
   "model": "Vogue Max Combi C40",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 16.4,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://images.ctfassets.net/sj902orc9wh4/79dU3jzgVhmf0PBfYqT8JR/ec0de733618104ead93ba31b0321fbb2/Vogue_MAX_Combi_FO.png?w=480&h=737&q=50&fm=png&bg=transparent",
   "availability": "available",
   "description": "Ideal Vogue Max Combi C40 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "40 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4395,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecofit-835",
   "priority": 21,
   "manufacturer": "Vaillant",
   "model": "ecoFIT pure 835",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://professional.vaillant.co.uk/images/products/boilers/ecofit-pure/ecofit-pure-combi-2576892-format-flex-height.jpg",
   "availability": "available",
   "description": "Vaillant ecoFIT pure 835 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "35 kW hot-water output",
    "Horizontal flue included",
    "Boiler protection kit included"
   ],
   "price": 3945,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-pro-24",
   "priority": 22,
   "manufacturer": "Vaillant",
   "model": "ecoTEC pro 24",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC pro 24 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3515,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-pro-28",
   "priority": 23,
   "manufacturer": "Vaillant",
   "model": "ecoTEC pro 28",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC pro 28 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3610,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-pro-30",
   "priority": 24,
   "manufacturer": "Vaillant",
   "model": "ecoTEC pro 30",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC pro 30 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3670,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-plus-826",
   "priority": 25,
   "manufacturer": "Vaillant",
   "model": "ecoTEC plus 826",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.6,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC plus 826 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "26 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4125,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-plus-832",
   "priority": 26,
   "manufacturer": "Vaillant",
   "model": "ecoTEC plus 832",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 13.1,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC plus 832 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "32 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4335,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "vaillant-ecotec-plus-836",
   "priority": 27,
   "manufacturer": "Vaillant",
   "model": "ecoTEC plus 836",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.7,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Vaillant ecoTEC plus 836 combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "36 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 4460,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-424",
   "priority": 28,
   "manufacturer": "Baxi",
   "model": "424 Combi (24kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-400-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 424 Combi (24kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3065,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-430",
   "priority": 29,
   "manufacturer": "Baxi",
   "model": "430 Combi (30kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-400-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 430 Combi (30kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3125,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-636",
   "priority": 30,
   "manufacturer": "Baxi",
   "model": "636 Combi 2 (36kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.7,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-600-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 636 Combi 2 (36kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "36 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3530,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-824",
   "priority": 31,
   "manufacturer": "Baxi",
   "model": "824 Combi 2 (24kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-800-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 824 Combi 2 (24kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Heating control included"
   ],
   "price": 3665,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-830",
   "priority": 32,
   "manufacturer": "Baxi",
   "model": "830 Combi 2 (30kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-800-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 830 Combi 2 (30kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Heating control included"
   ],
   "price": 3840,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "baxi-836",
   "priority": 33,
   "manufacturer": "Baxi",
   "model": "836 Combi 2 (36kW)",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.7,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://edge.sitecorecloud.io/bdrthermea1-platform-production-864a/media/Project/BaxiUK/BaxiUK/Images/Homeowner/Products/Boilers/Combi-boilers/baxi-800-combi-2-1-thumb.png?h=640&iar=0&w=640",
   "availability": "available",
   "description": "Baxi 836 Combi 2 (36kW) combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "36 kW hot-water output",
    "Horizontal flue included",
    "Smart thermostat included"
   ],
   "price": 4075,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "glowworm-compact-24",
   "priority": 34,
   "manufacturer": "Glow-worm",
   "model": "Compact 24kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.glow-worm.co.uk/images/products/boilers/compact-1/compact-2026-3118920-format-flex-height.png",
   "availability": "available",
   "description": "Glow-worm Compact 24kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2830,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "glowworm-compact-28",
   "priority": 35,
   "manufacturer": "Glow-worm",
   "model": "Compact 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.glow-worm.co.uk/images/products/boilers/compact-1/compact-2026-3118920-format-flex-height.png",
   "availability": "available",
   "description": "Glow-worm Compact 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2925,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "glowworm-energy-25",
   "priority": 36,
   "manufacturer": "Glow-worm",
   "model": "Energy 25C",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.2,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.glow-worm.co.uk/images/products/boilers/new-boiler-images-2023/energy-4/energy-combi-left-side-1-2787488-format-flex-height.png",
   "availability": "available",
   "description": "Glow-worm Energy 25C combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "25 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3500,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "glowworm-energy-30",
   "priority": 37,
   "manufacturer": "Glow-worm",
   "model": "Energy 30C",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://www.glow-worm.co.uk/images/products/boilers/new-boiler-images-2023/energy-4/energy-combi-left-side-1-2787488-format-flex-height.png",
   "availability": "available",
   "description": "Glow-worm Energy 30C combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3635,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "alpha-etec-nx-28",
   "priority": 38,
   "manufacturer": "Alpha",
   "model": "E-Tec NX 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://alpha-heating.ams3.digitaloceanspaces.com/wp-content/uploads/2023/09/27114127/etec-nx.png",
   "availability": "available",
   "description": "Alpha E-Tec NX 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2995,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "alpha-etec-nx-33",
   "priority": 39,
   "manufacturer": "Alpha",
   "model": "E-Tec NX 33kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 13.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://alpha-heating.ams3.digitaloceanspaces.com/wp-content/uploads/2023/09/27114127/etec-nx.png",
   "availability": "available",
   "description": "Alpha E-Tec NX 33kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "33 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3040,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "alpha-etec-plus-28",
   "priority": 40,
   "manufacturer": "Alpha",
   "model": "E-Tec NX Plus 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://alpha-heating.ams3.digitaloceanspaces.com/wp-content/uploads/2023/11/17150644/ETEC_PLUS_FACE_ON_FLAP_DOWN_RT_V2-e1700233622423.png",
   "availability": "available",
   "description": "Alpha E-Tec NX Plus 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3355,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "alpha-etec-plus-33",
   "priority": 41,
   "manufacturer": "Alpha",
   "model": "E-Tec NX Plus 33kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 13.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://alpha-heating.ams3.digitaloceanspaces.com/wp-content/uploads/2023/11/17150644/ETEC_PLUS_FACE_ON_FLAP_DOWN_RT_V2-e1700233622423.png",
   "availability": "available",
   "description": "Alpha E-Tec NX Plus 33kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "33 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3475,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "alpha-etec-plus-38",
   "priority": 42,
   "manufacturer": "Alpha",
   "model": "E-Tec NX Plus 38kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 15.6,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://alpha-heating.ams3.digitaloceanspaces.com/wp-content/uploads/2023/11/17150644/ETEC_PLUS_FACE_ON_FLAP_DOWN_RT_V2-e1700233622423.png",
   "availability": "available",
   "description": "Alpha E-Tec NX Plus 38kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "38 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3645,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "navien-ncb300-28",
   "priority": 43,
   "manufacturer": "Navien",
   "model": "NCB300 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://cdn.navien.co.uk/wp-content/uploads/2025/08/NCB300-combi-angle-682.png",
   "availability": "available",
   "description": "Navien NCB300 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 2805,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "navien-ncb300-37",
   "priority": 44,
   "manufacturer": "Navien",
   "model": "NCB300 37kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 15.2,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://cdn.navien.co.uk/wp-content/uploads/2025/08/NCB300-combi-angle-682.png",
   "availability": "available",
   "description": "Navien NCB300 37kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "37 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 2915,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "navien-ncb300-41",
   "priority": 45,
   "manufacturer": "Navien",
   "model": "NCB300 41kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 16.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": "https://cdn.navien.co.uk/wp-content/uploads/2025/08/NCB300-combi-angle-682.png",
   "availability": "available",
   "description": "Navien NCB300 41kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "41 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3005,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-025-24",
   "priority": 46,
   "manufacturer": "Viessmann",
   "model": "Vitodens 025-W 24kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 9.8,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 025-W 24kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "24 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2830,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-025-28",
   "priority": 47,
   "manufacturer": "Viessmann",
   "model": "Vitodens 025-W 28kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 11.5,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 025-W 28kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "28 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 2870,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-050-25",
   "priority": 48,
   "manufacturer": "Viessmann",
   "model": "Vitodens 050-W 25kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.2,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 050-W 25kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "25 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3150,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-050-30",
   "priority": 49,
   "manufacturer": "Viessmann",
   "model": "Vitodens 050-W 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 050-W 30kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3370,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-050-35",
   "priority": 50,
   "manufacturer": "Viessmann",
   "model": "Vitodens 050-W 35kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 050-W 35kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "35 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3425,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-100-26",
   "priority": 51,
   "manufacturer": "Viessmann",
   "model": "Vitodens 100-W 26kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 10.6,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 100-W 26kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "26 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3560,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-100-30",
   "priority": 52,
   "manufacturer": "Viessmann",
   "model": "Vitodens 100-W 30kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 12.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 100-W 30kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue and a magnetic system filter.",
   "benefits": [
    "30 kW hot-water output",
    "Horizontal flue included",
    "Magnetic system filter included"
   ],
   "price": 3715,
   "boiler_price": null,
   "installation_price": null
  },
  {
   "id": "viessmann-100-35",
   "priority": 53,
   "manufacturer": "Viessmann",
   "model": "Vitodens 100-W 35kW",
   "type": "combi",
   "fuel": "gas",
   "ch_kw": null,
   "dhw_flow_lpm": 14.3,
   "efficiency_pct": null,
   "erp": null,
   "warranty_years": null,
   "warranty_note": "Manufacturer's warranty applies. We register your new boiler with the manufacturer for you",
   "dimensions_mm": null,
   "image": null,
   "image_url": null,
   "availability": "available",
   "description": "Viessmann Vitodens 100-W 35kW combi boiler, supplied and fitted by our Gas Safe registered engineer with a horizontal flue.",
   "benefits": [
    "35 kW hot-water output",
    "Horizontal flue included"
   ],
   "price": 3745,
   "boiler_price": null,
   "installation_price": null
  }
 ],
 "conversion": {
  "id": "conversion",
  "label": "Convert to a combi boiler",
  "description": "We remove your hot water cylinder and tanks and alter the pipework so a combi can be fitted.",
  "price": 940
 },
 "moves": [
  {
   "id": "same_room",
   "label": "Same room, different position",
   "price": 1095
  },
  {
   "id": "utility",
   "label": "Utility room",
   "price": 1294
  },
  {
   "id": "kitchen",
   "label": "Kitchen",
   "price": 1294
  },
  {
   "id": "garage",
   "label": "Garage",
   "price": 1294
  },
  {
   "id": "airing",
   "label": "Airing cupboard",
   "price": 1294
  },
  {
   "id": "bedroom",
   "label": "Bedroom",
   "price": 1294
  },
  {
   "id": "loft",
   "label": "Loft or attic",
   "price": 1493
  },
  {
   "id": "other",
   "label": "Somewhere else",
   "price": null
  }
 ],
 "extras": [
  {
   "id": "flush",
   "group": "care",
   "label": "Heating system flush",
   "description": "An in-depth clean of your heating system to improve efficiency and help your new boiler last.",
   "price": 198,
   "max": 1
  },
  {
   "id": "scale",
   "group": "care",
   "label": "In-line scale reducer",
   "description": "Helps stop limescale forming in your boiler and pipework. Worth having in a hard water area.",
   "price": 65,
   "max": 1
  },
  {
   "id": "trv",
   "group": "rads",
   "label": "Thermostatic radiator valve (TRV)",
   "description": "Set the temperature room by room. Building Regulations expect one on every radiator except in the room with the main thermostat.",
   "price": 40,
   "max": 20,
   "unit": "each"
  },
  {
   "id": "rad",
   "group": "rads",
   "label": "Replace a radiator (like for like)",
   "description": "Swap an old radiator for a new one of the same size, with a TRV fitted.",
   "price": 149,
   "max": 10,
   "unit": "each"
  },
  {
   "id": "ctl_wifi",
   "group": "controls",
   "exclusive": true,
   "label": "Wi-Fi smart thermostat",
   "description": "Control your heating from your phone.",
   "price": 79,
   "max": 1
  },
  {
   "id": "ctl_smart",
   "group": "controls",
   "exclusive": true,
   "label": "Advanced smart thermostat",
   "description": "A smart thermostat designed to give you more control and cut your gas use.",
   "price": 99,
   "max": 1
  },
  {
   "id": "ctl_hive",
   "group": "controls",
   "exclusive": true,
   "label": "Hive Thermostat Mini",
   "description": "Hive's smart thermostat, supplied and set up for you.",
   "price": 267,
   "max": 1
  },
  {
   "id": "ctl_reconnect",
   "group": "controls",
   "exclusive": true,
   "label": "Reconnect my existing Hive or Nest",
   "description": "You must already own it. We reconnect it to your new boiler on the day.",
   "price": 5,
   "max": 1
  }
 ],
 "groups": {
  "care": "System care",
  "rads": "Radiators and valves",
  "controls": "Heating controls"
 },
 "included": [
  "Installation by a Gas Safe registered engineer",
  "Removal and disposal of your old boiler",
  "Standard flue kit for your new boiler",
  "Programmable room thermostat",
  "Testing, commissioning and a walk-through of the controls"
 ]
};
